name: リリース

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  release:
    name: Release
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get Version
        id: package-version
        run: echo '::set-output name=VERSION::'$(node -e "console.log(require(\"./package.json\").version)")

      - name: Checkout and Push
        env:
          VERSION: ${{ steps.package-version.outputs.VERSION }}
        run: |
          git tag v${VERSION}
          git push origin v${VERSION}

          git checkout develop
          git merge origin/release-v${VERSION}
          git push origin develop

          git push origin :release-v${VERSION}
