name: リリース

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set Config
        run: |
          git config --global user.email "amotarao@users.noreply.github.com"
          git config --global user.name "Amon Sawamura"¥

      - name: Bump Version
        run: yarn version --patch

      - name: show log
        run: git log --oneline

      - name: Get Version
        id: package-version
        run: echo '::set-output name=VERSION::'$(node -e "console.log(require(\"./package.json\").version)")

      - name: Checkout and Push
        run: |
          git checkout -b release-v${{ steps.package-version.outputs.VERSION }}
          git push origin release-v${{ steps.package-version.outputs.VERSION }} -f
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Create Pull Request
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -u amotarao:${GITHUB_TOKEN} \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls \
          -d '{"title":"Release: v${{ steps.package-version.outputs.VERSION }}","head":"bump-v${{ steps.package-version.outputs.VERSION }}","base":"main"}'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
