name: リリース

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Set Config
        run: |
          git config --global user.email "amotarao@users.noreply.github.com"
          git config --global user.name "Amon Sawamura"

      - name: Bump Version
        run: yarn version --patch

      - name: show log
        run: git log --oneline

      - name: Get Version
        id: package-version
        run: echo '::set-output name=VERSION::'$(node -e "console.log(require(\"./package.json\").version)")

      - name: Checkout release
        run: git checkout -b bump-v${{ steps.package-version.outputs.VERSION }}

      - name: Push
        run: git push origin bump-v${{ steps.package-version.outputs.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          title: Bump to v${{ steps.package-version.outputs.VERSION }}
          body: ""
          base: main
          branch: bump-v${{ steps.package-version.outputs.VERSION }}
